name: flutter_layout_grid_examples
description: Examples for flutter_layout_grid.
private: true

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid:
    path: ../
  google_fonts: ^1.0.0
  quiver: ^2.1.5
  url_launcher: ^5.7.0

flutter:
  assets:
    - periodic_table_data.json
