version: 2.1
executors:
  dart_sdk_image:
    docker:
      - image: google/dart
  flutter_sdk_image:
    docker:
      - image: cirrusci/flutter:dev

jobs:
  test:
    executor: flutter_sdk_image
    steps:
      - checkout
      - run: tool/ci_test.sh

workflows:
  version: 2.1
  default:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
